---
kind: pipeline
type: docker
name: Java Maven Deploy

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: settings
    image: md5lukas/drone-mvn-settings
    settings:
      servers:
        - id: woolgens
          username: woolgens
      serverSecrets:
        from_secret: WOOLGENS_NEXUS_CREDENTIALS
  - name: testing
    depends_on: [settings]
    image: maven
    commands:
      - mvn test -B -s settings.xml
  - name: deploy
    image: maven
    commands:
      - mvn deploy -B -s settings.xml
